name: Node.js CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

env:
  IMAGE_NAME: sergejparity/polkadot-basic-notification

jobs:
  check-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm ci --ignore-scripts

      - name: Run linting
        run: npm run lint
        # TODO: currently fails, need fix
        continue-on-error: true

  build-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm ci --ignore-scripts

      - name: Build npm
        run: npm run build

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Copy build artifacts
        run: cp -r build/ artifacts/

      - name: Display artifacts
        run: ls artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: npm-build-artifacts
          path: artifacts

  build-only-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download npm build artifacts
        uses: actions/download-artifact@v3
        with:
          name: npm-build-artifacts

      - name: Build Docker image
        run: |
          export VERSION=$(if [ "$CI_COMMIT_REF_NAME" == "master" ]; then echo "master-${CI_COMMIT_SHORT_SHA}"; else echo "$CI_COMMIT_REF_NAME"; fi)
          docker build --build-arg VCS_REF="${GITHUB_SHA}" \
                       --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')" \
                       --build-arg PROJECT_NAME="${GITHUB_REPOSITORY}" \
                       -t "${{ secrets.DOCKER_USER }}/polkadot-basic-notification:latest" \
                       -t "${{ secrets.DOCKER_USER }}/polkadot-basic-notification:$VERSION" \
                       -f injected.Containerfile .

  build-docker:
    runs-on: ubuntu-latest
    needs:
      - check-linting
      - build-npm

    steps:
      - name: Set up Buildah environment
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download npm build artifacts
        uses: actions/download-artifact@v3
        with:
          name: npm-build-artifacts
          path: artifacts

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          context: ./artifacts
          file: ./injected.Containerfile
          build-args: |
            VCS_REF="${{ github.sha }}"
            BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
            PROJECT_NAME="${{ github.repository }}"
          tags: |
            ${{ env.IMAGE_NAME }}:latest

      # - name: Build Docker image
      #   run: |
      #     export VERSION=$(if [ "$CI_COMMIT_REF_NAME" == "master" ]; then echo "master-${CI_COMMIT_SHORT_SHA}"; else echo "$CI_COMMIT_REF_NAME"; fi)
      #     docker build --build-arg VCS_REF="${GITHUB_SHA}" --build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')" --build-arg IMAGE_NAME="${GITHUB_REPOSITORY}" -t "${{ secrets.DOCKER_USER }}/polkadot-basic-notification:latest" -t "${{ secrets.DOCKER_USER }}/polkadot-basic-notification:$VERSION" -f injected.Containerfile .

  build-push-image:
    name: Build and push Docker image
    if: ${{ github.ref == 'refs/heads/master' ||  github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    environment: master_and_tags
    needs:
      - check-linting
      - build-npm

    steps:
      - name: Set up Buildah environment
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download npm build artifacts
        uses: actions/download-artifact@v3
        with:
          name: npm-build-artifacts
          path: artifacts

      - name: Prepare Docker environment
        run: |
          echo IMAGE_TAG=$(if [ "$GITHUB_REF" == "refs/heads/master" ]; then echo "master-${GITHUB_SHA::7}"; else echo "$GITHUB_REF_NAME"; fi) >> $GITHUB_ENV
          echo "Docker image will be published with the tag: ${{ env.IMAGE_TAG }}!"

      - name: Log in to Docker Hub
        if: ${{ github.ref == 'refs/heads/master' ||  github.ref_type == 'tag' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./artifacts
          file: ./injected.Containerfile
          build-args: |
            VCS_REF="${{ github.sha }}"
            BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
            IMAGE_NAME="${IMAGE_NAME}"
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest



      # - name: Build and push Docker image
      #   run: |
      #     export VERSION=$(if [ "$CI_COMMIT_REF_NAME" == "master" ]; then echo "master-${CI_COMMIT_SHORT_SHA}"; else echo "$CI_COMMIT_REF_NAME"; fi)
      #     echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      #     docker push "${{ secrets.DOCKER_USER }}/polkadot-basic-notification:latest"
      #     docker push "${{ secrets.DOCKER_USER }}/polkadot-basic-notification:$VERSION"
